--- 
excluded_pkgfiles: []

project_pubdir: /usr/local/www/public/code
project_pubhost: deveiate
project_homepage: http://deveiate.org/projects/BlueCloth/
project_requirements: {}

release_smtphost: mail.faeriemud.org
project_description: |-
  BlueCloth is a Ruby implementation of [Markdown][1], a text-to-HTML conversion
  tool for web writers. To quote from the project page: Markdown allows you to
  write using an easy-to-read, easy-to-write plain text format, then convert it to
  structurally valid XHTML (or HTML).
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: {}

project_summary: BlueCloth is a Ruby implementation of Markdown
version_file: bluecloth.rb
additional_pkgfiles: 
- LICENSE.discount
- spec/data/**/*.{txt,text,html}
- ext/VERSION
dev_dependencies: 
  rake-compiler: ">= 0.7.0"
authors: 
  Michael Granger: ged@FaerieMUD.org
post_install_message: ""
project_name: BlueCloth
